### ISSUE TITLE
options={} in function parameter only works when it is the first parameter

### ISSUE THREAD

**Issue by naiduv** [jperry/teamcity-ruby-client#40]
For some reason this syntax :project_name => project_name, when calling a function does not work if options = {} is not the first parameter in the function.

For instance, 

TeamCity.create_build_step(buildtype_id => build_type, type:'MsBuild', name: 'Unit Tests')

..eats up the :type and it can't be fetched inside the called function. So I had to use

TeamCity.create_build_step(build_type, type:'MsBuild', name: 'Unit Tests')

Not sure why that is, or if its a ruby version problem...

Anyway, your api is awesome and I have yet to find anything that I need to write myself. Totally a life saver.

**Comment by jperry** [comment]
thanks @naiduv - is still still an issue?

**Comment by jperry** [comment]
@naiduv - checking one last time before closing.  Is this still an issue or ruby version specific?  Please provide more information about your environment, what ruby version, basically how to reproduce.  Thanks!

**Comment by naiduv** [comment]
Sorry I have not used chef in quite a while.
Please disregard.

**Comment by jperry** [comment]
thx
